# Use the official Python image as the base image
FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

# Copy the rest of the application code into the container
COPY . .

# Command to run your Python application (replace "app.py" with your application's entry point)
CMD ["python3", "main.py"]
